FROM maven:3.8.5-jdk-11

# Install Chrome and ChromeDriver
RUN apt-get update && apt-get install -y wget unzip \
    && wget -N https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && apt install -y ./google-chrome-stable_current_amd64.deb \
    && wget -N https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip \
    && unzip chromedriver_linux64.zip \
    && mv chromedriver /usr/local/bin/ \
    && chmod +x /usr/local/bin/chromedriver

# Verify installations
RUN google-chrome --version && chromedriver --version


#docker build -t reka83/maven-chrome -f Dockerfile-maven-chrome .
#build and push this image to Docker Hub
#docker build -t your_dockerhub_username/maven-chrome:latest .
#docker push your_dockerhub_username/maven-chrome:latest