pipeline {

  agent any  // Use any available agent (Linux in this case)

  stages {

    stage('Checkout') {
      steps {
        sh 'echo passed'  // Use 'sh' if on Linux , 'bat' if on Windows 
        git branch: 'master', url: 'https://github.com/Rekapost/TestNG_Framework.git'
      }
    }

    stage('Build and Test') {
      steps {
        sh 'mvn clean test -Dsurefire.suiteXmlFiles=testng.xml'  // Use 'sh' if on Linux
      }
    }
  }
}


/*
pipeline {
    agent any
    stages {
        stage('Build and Test') {
            steps {
                bat 'C:\\Users\\nreka\\git\\repository\\Testng_Framework\\run.bat'
            }
        }
    }
}
*/