pipeline {
  agent none  // No global agent; define per stage

  stages {
    stage('Checkout') {
      agent { docker { image 'maven:3.8.5-jdk-11' } }
      steps {
        sh 'echo passed'
        git branch: 'master', url: 'https://github.com/Rekapost/TestNG_Framework.git'
      }
    }

    stage('Build and Test') {
      agent { docker { image 'selenium/standalone-chrome:latest' } }
      steps {
        sh 'mvn clean test -Dsurefire.suiteXmlFiles=testng.xml'
      }
    }
  }
}



/*
pipeline {
    agent any
    stages {
        stage('Build and Test') {
            steps {
                bat 'C:\\Users\\nreka\\git\\repository\\Testng_Framework\\run.bat'
            }
        }
    }
}
*/